#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Carga todos los scripts de la carpeta auto-load:
for DOTFILE in `find ~/dotfiles/auto-load/ -type f -name .*`
do
  source $DOTFILE
done

# ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

#powerline
if [[ -r ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh ]]; then
    source ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
fi



