#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# Carga todos los scripts de la carpeta .dotfiles: 

for DOTFILE in `find /home/viroide/.dotfiles/auto-load/`
do
  source $DOTFILE
done




